import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar configuration for the Physical AI & Humanoid Robotics Book
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'module-1-ros2/index',
        'module-1-ros2/chapter-1-ros2-overview',
        'module-1-ros2/chapter-2-nodes-topics-services',
        'module-1-ros2/chapter-3-urdf-humanoids',
      ],
      collapsed: false,
    },
    // Additional modules will be added here as they are developed
  ],
};

export default sidebars;
